# Generated by Django 4.2.30 on 2026-07-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FACE_UNKNOWN', '陌生人'), ('INTRUSION', '区域闯入'), ('PROXIMITY', '距离过近'), ('LOITER', '异常停留'), ('TAILGATE', '尾随进入'), ('FIRE', '火情'), ('WATER', '积水'), ('FALL', '人员摔倒')], max_length=32, verbose_name='告警类型')),
                ('level', models.CharField(choices=[('HIGH', '高'), ('MEDIUM', '中'), ('LOW', '低')], default='MEDIUM', max_length=16, verbose_name='严重等级')),
                ('stream_id', models.CharField(default='living_room', max_length=32, verbose_name='视频流ID')),
                ('description', models.TextField(blank=True, verbose_name='告警描述')),
                ('snapshot_path', models.CharField(blank=True, help_text='告警时刻的截图文件路径', max_length=256, verbose_name='截图路径')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('handled', '已处理'), ('ignored', '已忽略')], default='pending', max_length=16, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处置时间')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.household', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
                'db_table': 'alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
