# Generated by Codex on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="type",
            field=models.CharField(
                choices=[
                    ("FACE_UNKNOWN", "陌生人"),
                    ("FACE_SPOOF", "人脸欺骗攻击"),
                    ("FACE_REPLAY", "照片/视频重放攻击"),
                    ("FACE_DEEPFAKE", "AI换脸攻击"),
                    ("FACE_AUTH_FAILED", "人脸认证失败"),
                    ("INTRUSION", "区域闯入"),
                    ("PROXIMITY", "距离过近"),
                    ("LOITER", "异常停留"),
                    ("TAILGATE", "尾随进入"),
                    ("FIRE", "火情"),
                    ("WATER", "积水"),
                    ("FALL", "人员摔倒"),
                ],
                max_length=32,
                verbose_name="告警类型",
            ),
        ),
    ]
