# Generated by Django 4.2.30 on 2026-07-07 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='区域名称')),
                ('stream_id', models.CharField(choices=[('living_room', '客厅'), ('kitchen', '厨房')], default='living_room', max_length=32, verbose_name='关联视频流')),
                ('points_json', models.JSONField(help_text='JSON 数组，如 [[x1,y1], [x2,y2], [x3,y3], ...]', verbose_name='多边形顶点')),
                ('forbidden_roles', models.JSONField(default=list, help_text="如 ['child'] 表示小孩禁止进入该区域", verbose_name='禁止进入的角色')),
                ('safe_distance', models.IntegerField(default=50, help_text='小于此距离触发 PROXIMITY 告警', verbose_name='安全距离(px)')),
                ('dwell_time', models.IntegerField(default=5, help_text='停留超过此时长触发 LOITER 告警', verbose_name='停留阈值(秒)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('household', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='households.household', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '安防区域',
                'verbose_name_plural': '安防区域',
                'db_table': 'zone',
                'ordering': ['-created_at'],
            },
        ),
    ]
