# Generated by Django 4.2.30 on 2026-07-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FACE_MATCHED', '人脸识别成功'), ('FACE_UNKNOWN', '陌生人出现'), ('INTRUSION', '区域闯入'), ('PROXIMITY', '距离过近'), ('LOITER', '异常停留'), ('TAILGATE', '尾随'), ('LOCK', '上锁'), ('SYSTEM', '系统事件')], max_length=32, verbose_name='事件类型')),
                ('stream_id', models.CharField(default='living_room', max_length=32, verbose_name='视频流ID')),
                ('description', models.CharField(max_length=256, verbose_name='事件描述')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='如识别到的成员ID、姓名等', verbose_name='附加数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
            ],
            options={
                'verbose_name': '事件日志',
                'verbose_name_plural': '事件日志',
                'db_table': 'event_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
