# Generated by Django 4.2.30 on 2026-07-07 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：张三家、李四家', max_length=64, unique=True, verbose_name='家庭名称')),
                ('address', models.CharField(blank=True, help_text='可选，如：3栋501', max_length=256, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '家庭',
                'verbose_name_plural': '家庭',
                'db_table': 'household',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.ForeignKey(help_text='该登录账号属于哪个家庭', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.household', verbose_name='所属家庭')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展',
                'verbose_name_plural': '用户扩展',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('role', models.CharField(choices=[('adult', '成人'), ('child', '小孩'), ('elder', '老人'), ('guest', '访客')], default='adult', max_length=16, verbose_name='角色')),
                ('student_id', models.CharField(blank=True, max_length=32, verbose_name='学号/工号')),
                ('face_encoding', models.JSONField(blank=True, help_text='dlib 提取的 128 维特征向量，JSON 数组格式', null=True, verbose_name='人脸编码(128维)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.household', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '家庭成员',
                'verbose_name_plural': '家庭成员',
                'db_table': 'family_member',
                'ordering': ['-created_at'],
                'unique_together': {('household', 'student_id')},
            },
        ),
    ]
