# Generated by Django 4.2.30 on 2026-07-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('role', models.CharField(choices=[('adult', '成人'), ('child', '小孩'), ('elder', '老人'), ('guest', '访客')], default='adult', max_length=16, verbose_name='角色')),
                ('student_id', models.CharField(blank=True, max_length=32, unique=True, verbose_name='学号/工号')),
                ('face_encoding', models.JSONField(blank=True, help_text='dlib 提取的 128 维特征向量，JSON 数组格式', null=True, verbose_name='人脸编码(128维)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '家庭成员',
                'verbose_name_plural': '家庭成员',
                'db_table': 'family_member',
                'ordering': ['-created_at'],
            },
        ),
    ]
