# Generated by Django 4.2.30 on 2026-07-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='昵称'),
        ),
    ]
